##
#   .oooooo..o oooo         o8o                .oooooo.                                         .o8
#  d8P'    `Y8 `888         `"'               d8P'  `Y8b                                       "888
#  Y88bo.       888  oooo  oooo  ooo. .oo.   888           oooo  oooo   .oooo.   oooo d8b  .oooo888
#   `"Y8888o.   888 .8P'   `888  `888P"Y88b  888           `888  `888  `P  )88b  `888""8P d88' `888
#       `"Y88b  888888.     888   888   888  888     ooooo  888   888   .oP"888   888     888   888
#  oo     .d8P  888 `88b.   888   888   888  `88.    .88'   888   888  d8(  888   888     888   888
#  8""88888P'  o888o o888o o888o o888o o888o  `Y8bood8P'    `V88V"V8P' `Y888""8o d888b    `Y8bod88P"
##

name: SkinGuard
main: Kronnosy\SkinGuard\SkinGuard

api: 5.0.0
version: 1.0.0

author: "Kronnosy"
website: "https://github.com/Kronnosy"
description: "SkinGuard is a plugin that protects players from invalid skins and 4D skins."
